name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.URL }}

    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/ThePrimeJnr
            git pull origin main
            npm install --production
            npm run build
            pm2 restart theprimejnr
